name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Ruby 3.x
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2

      - name: Install dependencies
        run: make install

      - name: Run Rubocop
        run: make lint

      - name: Run Slim Lint
        run: make slim_lint

      - name: Run tests
        run: make test