name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Ruby 3.x
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2

      - name: Install dependencies
        run: bundle install

      - name: Run Rubocop
        run: bundle exec rubocop

      - name: Run Slim Lint
        run: bundle exec slim-lint

      - name: Run tests
        run: bundle exec rails test