name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
      branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Ruby 3.x
        uses: actions/checkout@v3
        with:
          ruby-version: 3.2.2
          bundler-cache: true

      - name: Install bundler dependencies
        run: make install

      - name: Run yarn install
        run: make yarn_install

      - name: Run Rubocop
        run: make lint_rubocop

      - name: Run Slim Lint
        run: make lint_slim

      - name: Run tests
        run: make test